const copy = {
  en: {
    title: 'Equb & Iddir', subtitle: 'Contributions, turns and obligations', accountingTitle: 'Accounting that stays honest', accountingBody: 'Equb contributions build a claim. A payout reduces that claim and an early payout shows a remaining obligation. Iddir is spending unless you mark it recoverable. Fees remain expenses.', firstTitle: 'Add your first group', firstBody: 'Track each payment, payout turn and missed contribution without inflating income.', firstButton: 'Create Equb or Iddir', smsMatches: 'Possible SMS matches', newGroup: 'New community group', type: 'Type', equbSavings: 'Equb savings', iddirSupport: 'Iddir support', groupName: 'Group name', groupPlaceholder: 'e.g. Family Equb', account: 'Account', eachContribution: 'Each contribution', rounds: 'Rounds', frequency: 'Frequency', weekly: 'Weekly', monthly: 'Monthly', gregorianStart: 'Gregorian start (YYYY-MM-DD)', ethiopianStart: 'Ethiopian start (YYYY-MM-DD, optional)', payoutTurn: 'My payout turn', expectedPayout: 'Expected payout', membersInput: 'Members (one per line: Name:Turn:Phone)', recoverable: 'Recoverable contribution', recoverableBody: 'Use only when the group owes this money back.', reminders: 'Contribution reminders', daysBefore: 'Days before', saving: 'Saving…', createSchedule: 'Create schedule', record: 'Record', payout: 'payout', contribution: 'contribution', principal: 'Principal amount', bankFee: 'Bank/service fee', feeBody: 'Principal and bank fee are saved separately.', cancel: 'Cancel', save: 'Save', contributed: 'Contributed', payouts: 'Payouts', remaining: 'Remaining', obligation: 'Obligation', claim: 'Claim', spent: 'Spent', yourTurn: 'Your turn', members: 'Members', payBalance: 'Pay balance', recordPayment: 'Record payment', missed: 'Missed', recordPayout: 'Record payout', undo: 'Undo last', reopen: 'Reopen', markDefault: 'Mark default', possible: 'possible', confidence: 'confidence', reviewSms: 'Review SMS before linking', close: 'Close group form', back: 'Go back', create: 'Create group', reminderTitle: 'contribution due', reminderBody: 'is due', couldNotSave: 'Could not save', retry: 'Please retry.',
  },
  es: {
    title: 'Equb e Iddir', subtitle: 'Aportes, turnos y obligaciones', accountingTitle: 'Contabilidad clara', accountingBody: 'Los aportes de Equb crean un derecho. El pago lo reduce y un pago anticipado muestra la obligación restante. Iddir es un gasto salvo que se marque como recuperable. Las comisiones siguen siendo gastos.', firstTitle: 'Añade tu primer grupo', firstBody: 'Registra cada aporte, turno de pago y cuota perdida sin inflar los ingresos.', firstButton: 'Crear Equb o Iddir', smsMatches: 'Posibles coincidencias de SMS', newGroup: 'Nuevo grupo comunitario', type: 'Tipo', equbSavings: 'Ahorro Equb', iddirSupport: 'Apoyo Iddir', groupName: 'Nombre del grupo', groupPlaceholder: 'p. ej. Equb familiar', account: 'Cuenta', eachContribution: 'Cada aporte', rounds: 'Rondas', frequency: 'Frecuencia', weekly: 'Semanal', monthly: 'Mensual', gregorianStart: 'Inicio gregoriano (AAAA-MM-DD)', ethiopianStart: 'Inicio etíope (AAAA-MM-DD, opcional)', payoutTurn: 'Mi turno de pago', expectedPayout: 'Pago esperado', membersInput: 'Miembros (una línea: Nombre:Turno:Teléfono)', recoverable: 'Aporte recuperable', recoverableBody: 'Úsalo solo cuando el grupo deba devolver el dinero.', reminders: 'Recordatorios de aportes', daysBefore: 'Días antes', saving: 'Guardando…', createSchedule: 'Crear calendario', record: 'Registrar', payout: 'pago', contribution: 'aporte', principal: 'Importe principal', bankFee: 'Comisión bancaria', feeBody: 'El principal y la comisión se guardan por separado.', cancel: 'Cancelar', save: 'Guardar', contributed: 'Aportado', payouts: 'Pagos', remaining: 'Pendiente', obligation: 'Obligación', claim: 'Derecho', spent: 'Gastado', yourTurn: 'Tu turno', members: 'Miembros', payBalance: 'Pagar saldo', recordPayment: 'Registrar pago', missed: 'Perdido', recordPayout: 'Registrar pago recibido', undo: 'Deshacer último', reopen: 'Reabrir', markDefault: 'Marcar incumplido', possible: 'posible', confidence: 'confianza', reviewSms: 'Revisar SMS antes de vincular', close: 'Cerrar formulario', back: 'Volver', create: 'Crear grupo', reminderTitle: 'aporte pendiente', reminderBody: 'vence', couldNotSave: 'No se pudo guardar', retry: 'Inténtalo de nuevo.',
  },
  am: {
    title: 'እቁብ እና እድር', subtitle: 'መዋጮ፣ ተራ እና ግዴታ', accountingTitle: 'ግልጽ ሂሳብ', accountingBody: 'የእቁብ መዋጮ የተቀማጭ መብት ይፈጥራል። ዕጣ ሲወጣ መብቱ ይቀንሳል፣ ቀድሞ ከወጣም ቀሪ ግዴታ ይታያል። የእድር መዋጮ ተመላሽ ካልተባለ ወጪ ነው። ክፍያዎችም ወጪ ናቸው።', firstTitle: 'የመጀመሪያ ቡድን ያክሉ', firstBody: 'ገቢን ሳያጋንኑ መዋጮ፣ የዕጣ ተራ እና ያመለጠ ክፍያ ይከታተሉ።', firstButton: 'እቁብ ወይም እድር ፍጠር', smsMatches: 'ሊዛመዱ የሚችሉ SMS', newGroup: 'አዲስ ማህበረሰብ ቡድን', type: 'ዓይነት', equbSavings: 'የእቁብ ቁጠባ', iddirSupport: 'የእድር ድጋፍ', groupName: 'የቡድን ስም', groupPlaceholder: 'ለምሳሌ የቤተሰብ እቁብ', account: 'ሂሳብ', eachContribution: 'እያንዳንዱ መዋጮ', rounds: 'ዙሮች', frequency: 'ድግግሞሽ', weekly: 'ሳምንታዊ', monthly: 'ወርሃዊ', gregorianStart: 'የጎርጎርዮሳዊ መጀመሪያ (YYYY-MM-DD)', ethiopianStart: 'የኢትዮጵያ መጀመሪያ (YYYY-MM-DD፣ አማራጭ)', payoutTurn: 'የእኔ የዕጣ ተራ', expectedPayout: 'የሚጠበቅ ዕጣ', membersInput: 'አባላት (በየመስመሩ ስም:ተራ:ስልክ)', recoverable: 'ተመላሽ መዋጮ', recoverableBody: 'ቡድኑ ገንዘቡን መመለስ ሲኖርበት ብቻ ይጠቀሙ።', reminders: 'የመዋጮ ማስታወሻ', daysBefore: 'ከስንት ቀን በፊት', saving: 'በማስቀመጥ ላይ…', createSchedule: 'መርሐግብር ፍጠር', record: 'መዝግብ', payout: 'ዕጣ', contribution: 'መዋጮ', principal: 'ዋና መጠን', bankFee: 'የባንክ/አገልግሎት ክፍያ', feeBody: 'ዋናው ገንዘብ እና የባንክ ክፍያ ተለያይተው ይቀመጣሉ።', cancel: 'ሰርዝ', save: 'አስቀምጥ', contributed: 'የተዋጣ', payouts: 'የወጣ ዕጣ', remaining: 'ቀሪ', obligation: 'ግዴታ', claim: 'መብት', spent: 'ወጪ', yourTurn: 'የእርስዎ ተራ', members: 'አባላት', payBalance: 'ቀሪውን ክፈል', recordPayment: 'ክፍያ መዝግብ', missed: 'አልተከፈለም', recordPayout: 'ዕጣ መዝግብ', undo: 'የመጨረሻውን ቀልብስ', reopen: 'እንደገና ክፈት', markDefault: 'እንደተቋረጠ ምልክት', possible: 'ሊሆን የሚችል', confidence: 'እርግጠኝነት', reviewSms: 'ከማያያዝ በፊት SMS ይገምግሙ', close: 'ቅጹን ዝጋ', back: 'ተመለስ', create: 'ቡድን ፍጠር', reminderTitle: 'መዋጮ ደርሷል', reminderBody: 'መክፈያው ደርሷል', couldNotSave: 'ማስቀመጥ አልተቻለም', retry: 'እንደገና ይሞክሩ።',
  },
  om: {
    title: 'Equb fi Iddir', subtitle: 'Gumaacha, dabaree fi dirqama', accountingTitle: 'Herrega ifaa', accountingBody: 'Gumaachi Equb mirga qusannoo uuma. Kaffaltiin mirga sana hir’isa; kaffaltiin duraa dirqama hafe agarsiisa. Iddir baasii dha, yoo deebifamu jechuun galmaa’e malee. Kaffaltiin tajaajilaas baasii dha.', firstTitle: 'Garee jalqabaa dabali', firstBody: 'Galii ol-kaasuu malee gumaacha, dabaree fi kaffaltii hafee hordofi.', firstButton: 'Equb ykn Iddir uumi', smsMatches: 'SMS wal-simuu danda’u', newGroup: 'Garee hawaasaa haaraa', type: 'Gosa', equbSavings: 'Qusannoo Equb', iddirSupport: 'Deeggarsa Iddir', groupName: 'Maqaa garee', groupPlaceholder: 'fkn. Equb maatii', account: 'Herrega', eachContribution: 'Gumaacha tokko', rounds: 'Marsaa', frequency: 'Irra deddeebii', weekly: 'Torbanitti', monthly: 'Ji’atti', gregorianStart: 'Jalqaba Giriigooriyaan (YYYY-MM-DD)', ethiopianStart: 'Jalqaba Itoophiyaa (YYYY-MM-DD, filannoo)', payoutTurn: 'Dabaree kaffaltii koo', expectedPayout: 'Kaffaltii eegamu', membersInput: 'Miseensota (Maqaa:Dabaree:Bilbila)', recoverable: 'Gumaacha deebifamu', recoverableBody: 'Yeroo gareen maallaqa deebisu qabu qofa fayyadami.', reminders: 'Yaadachiisa gumaachaa', daysBefore: 'Guyyaa dura', saving: 'Olkaa’aa jira…', createSchedule: 'Sagantaa uumi', record: 'Galmeessi', payout: 'kaffaltii', contribution: 'gumaacha', principal: 'Maallaqa ijoo', bankFee: 'Kaffaltii baankii', feeBody: 'Maallaqni ijoo fi kaffaltiin baankii addaan galmaa’u.', cancel: 'Dhiisi', save: 'Olkaa’i', contributed: 'Gumaachame', payouts: 'Kaffaltii', remaining: 'Hafe', obligation: 'Dirqama', claim: 'Mirga', spent: 'Baafame', yourTurn: 'Dabaree kee', members: 'Miseensota', payBalance: 'Hafaa kaffali', recordPayment: 'Kaffaltii galmeessi', missed: 'Hafe', recordPayout: 'Kaffaltii galmeessi', undo: 'Isa dhumaa deebisi', reopen: 'Irra deebi’i bani', markDefault: 'Kufaatii mallatteessi', possible: 'ta’uu danda’a', confidence: 'amanamummaa', reviewSms: 'Osoo hin hidhiin SMS ilaali', close: 'Unka cufi', back: 'Deebi’i', create: 'Garee uumi', reminderTitle: 'gumaachi gahe', reminderBody: 'gaheera', couldNotSave: 'Olkaa’uun hin danda’amne', retry: 'Irra deebi’i yaali.',
  },
  ti: {
    title: 'ዕቁብን ዕድርን', subtitle: 'ውጽኢት፣ ተራን ግዴታን', accountingTitle: 'ንጹር ሕሳብ', accountingBody: 'ውጽኢት ዕቁብ መሰል ዕቋር ይፈጥር። ዕጫ ነቲ መሰል ይንክዮ፣ ቀዲሙ እንተወጺኡ ድማ ዝተረፈ ግዴታ የርኢ። ዕድር ተመላሲ እንተዘይተባሂሉ ወጻኢ እዩ።', firstTitle: 'ቀዳማይ ጉጅለ ወስኽ', firstBody: 'እቶት ከይወሰኽካ ውጽኢት፣ ተራ ዕጫን ዝተረፈ ክፍሊትን ተኸታተል።', firstButton: 'ዕቁብ ወይ ዕድር ፍጠር', smsMatches: 'ክሰማማዕ ዝኽእል SMS', newGroup: 'ሓድሽ ማሕበረሰብ ጉጅለ', type: 'ዓይነት', equbSavings: 'ዕቋር ዕቁብ', iddirSupport: 'ደገፍ ዕድር', groupName: 'ስም ጉጅለ', groupPlaceholder: 'ንኣብነት ዕቁብ ስድራ', account: 'ሕሳብ', eachContribution: 'ነፍሲ ወከፍ ውጽኢት', rounds: 'ዙር', frequency: 'ድግግም', weekly: 'ሰሙናዊ', monthly: 'ወርሓዊ', gregorianStart: 'መጀመርታ ጎርጎርዮሳዊ (YYYY-MM-DD)', ethiopianStart: 'መጀመርታ ኢትዮጵያዊ (YYYY-MM-DD፣ ኣማራጺ)', payoutTurn: 'ተራ ዕጫይ', expectedPayout: 'ትጽቢት ዝግበረሉ ዕጫ', membersInput: 'ኣባላት (ስም:ተራ:ተሌፎን)', recoverable: 'ተመላሲ ውጽኢት', recoverableBody: 'ጉጅለ ገንዘብ ክመልስ ምስ ዝግባእ ጥራይ ተጠቐም።', reminders: 'መዘኻኸሪ ውጽኢት', daysBefore: 'መዓልቲ ቅድሚ', saving: 'ይዕቀብ ኣሎ…', createSchedule: 'መደብ ፍጠር', record: 'መዝግብ', payout: 'ዕጫ', contribution: 'ውጽኢት', principal: 'ቀንዲ መጠን', bankFee: 'ክፍሊት ባንኪ', feeBody: 'ቀንዲ ገንዘብን ክፍሊት ባንክን በበይኖም ይዕቀቡ።', cancel: 'ሰርዝ', save: 'ዓቅብ', contributed: 'ዝተዋጽአ', payouts: 'ዕጫ', remaining: 'ቀሪ', obligation: 'ግዴታ', claim: 'መሰል', spent: 'ወጻኢ', yourTurn: 'ተራኻ', members: 'ኣባላት', payBalance: 'ቀሪ ክፈል', recordPayment: 'ክፍሊት መዝግብ', missed: 'ዝተረፈ', recordPayout: 'ዕጫ መዝግብ', undo: 'ናይ መወዳእታ መልስ', reopen: 'እንደገና ክፈት', markDefault: 'ከም ዝተቋረጸ ምልክት', possible: 'ክኸውን ዝኽእል', confidence: 'እምነት', reviewSms: 'ቅድሚ ምትእስሳር SMS ርአ', close: 'ቅጥዒ ዕጸው', back: 'ተመለስ', create: 'ጉጅለ ፍጠር', reminderTitle: 'ውጽኢት በጺሑ', reminderBody: 'ግዜኡ በጺሑ', couldNotSave: 'ምዕቃብ ኣይተኻእለን', retry: 'ደጊምካ ፈትን።',
  },
} as const;

export type CommunityCopyKey = keyof typeof copy.en;
export const communityCopy = (language: string, key: CommunityCopyKey) => (copy[language as keyof typeof copy] || copy.en)[key] || copy.en[key];
